### ISSUE TITLE
все мои предложения

### ISSUE THREAD

**Issue by justqstn** [Sokol-Games-GmbH/PixelCombatsPublicApi#11]
здесь опишу то, что будет сделано за два года (если сделается вообще)
про все аргументы событий и методов я писать не буду, там будет интуитивно понятно

Rendering
будет иметь методы и свойства для изменения всяких параметров рендеринга, освещения

Rendering.Time = 10f; свойство, изменение времени на карте, чтобы можно было сделать ночь

Rendering.Fog = true; туман
также завести параметры тумана, по типу цвета, дальности тумана (на каком расстоянии туман начинается) и т.д

Rendering.DrawDistance = 100f; дальность прорисовки. пусть будет измеряться в юнитах

класс MapEditor
OnPlayerBreakBlock.Add(function(player, block)) - событие, когда игрок ломает блок

OnPlayerDamageBlock.Add(function(player, block, hp))  - событие, когда игрок наносит урон блоку (hp - хп блока что-ли, ну то есть блок же не сразу после удара ломается, только если включены слабые блоки)

OnPlayerPlacingBlock.Add(function(player, block, pos)) - события, когда игрок ставит блок. pos - позиция поставленного блока

класс Inventory
и тут хочу написать по поводу арендуемых оружий

уберите их насовсем, или оставьте лишь парочку, такие как всс, свд, дср, рпк, катана, керамбит, сайга, рпг, гранатомет, модифицированные оружия и другие, которые я не назвал
я думаю, что п90, скар, моссберг, тек9, револьвер это вполне обычные оружия
пусть они будут покупаться навсегда

цены:
п90 - 13000
скар - 20000
моссберг - 18000
тек9 - 12000
револьвер - 20000
также по поводу баланса оружий: нужно нерфить некоторые оружия, а именно всс и свд
всс - урон с 120 до 35
свд - урон с 120 до 90

SetMainWeapon(weaponid) - метод. изменяет оружие игрока в определенном слоте (main - основное, ну и по аналогии с остальными). если у игрока нет такого оружия, то оставляем то, что у него есть.
также и SetSecondaryWeapon, SetMeleeWeapon, SetExplosiveWeapon
GetMainWeapon() - метод, получаем оружие в определенном слоте (по аналогии с прошлым методом)
ReloadMainWeapon() - метод, перезаряжает оружие в определенном слоте (по аналогии с прошлым методом)

класс contextedProperties
Hp - проп, может быть использован только в контексте игрока. получаем текущее здоровье игрока, также имеем возможность  менять его. тип данных - float

класс Map
Current - возвращает объект с данными карты (айди, название, и т.д). например let cur_map = Map.Current; msg.Show(cur_map.Name) // Dusty2
LoadById - метод. загружает карту по ее айди на сервере

класс Teams
метод на удаление какой-либо команды. думаю, будет полезно

класс Log
нужен для вывода логов в отдельное окно, а именно то место, где пишутся всякие результаты выполнения команд
Debug(text) - выводит текст туда

Класс Chat
операции с чатом игры
Mute(player) - метод, запрещает игроку пользоваться чатом. при этом выводится сообщение в правой верхней части экрана
UnMute(player) - аналогично методу выше, только разрешает пользоваться
OnPlayerMessage.Add(function(player, message)) - событие, если игрок отправил сообщение
SendMessage(message) - метод,  отправляет текст в чат. будет пометка, что это сообщение от сервера, да так, чтобы все игроки поняли

класс Player
CurrentPosition - свойство, означает текущую позицию игрока. можно будет сделать, чтобы ее можно было менять. тогда будут возможны телепорты без спавнов
Disconnect(reason) - отключает игрока от сервера, выводя сообщение на экран

класс BuildBlocksSetEnum
AddBlocksSet(array) - метод, создает набор блоков. аргументом является массив с айдишниками блоков
GetBlocksSetArray(blocksset) - метод, возвращает массив с айди блоков. будет полезно для того, чтобы взять массив набора всех блоков, и убрать какие-либо.

класс Datastore
представляет собой класс для хранения каких-либо значений на сервере, чтобы после рестарта они не сбрасывались
Set(name, value) - метод, сохраняем value по name
Get(name) - метод, получаем значение по name

можно будет ограничить возможность записывать значения, дабы умник не написал цикл на огромное количество итераций и не засорял сервер

также у вас была идея для реализации покупок ака монетизации, такое тоже можно завезти, но если вы и хотите это - при обновлении сделайте так, чтобы у всех, у кого кого больше 500к серебра, было именно 500к серебра, типо вайпа, потому что сейчас экономика сломана
ваще экономику нужно править очень сильно

**Comment by HeadWagner** [comment]
Пе

**Comment by kkohno** [comment]
есть интересные идеи, которые скорее всего сделаем, однако лучше каждую оформить отдельной темой, чтобы мы могли по конкретной одной задаче отсортировать запросы и оценить
