### ISSUE TITLE
мои предложения #2

### ISSUE THREAD

**Issue by zjusttoxic** [Sokol-Games-GmbH/PixelCombatsPublicApi#5]
добавления в MapService
Map.Load(map id)  — загрузка карты по айди с сервера
Map.LoadList — загрузка списка карт
Map.Id — возвращает айди текущей карты в виде числа (будет полезно для всяких там приколюх)  
Map.Name — возвращает имя текущей карты в виде строки

добавления в PlayersApi
Player.GetHealth() — возвращает хп игрока
Player.SetHealth(int) — изменяет хп игрока
пример: player.SetHealth(player.GetHealth() + 30); player.Ui.Hint.Value = "Ваше хп: " + player.GetHealth();
думаю, это можно сделать через одно поле, но тут уже ты решай как хочешь
можно вообще это как проперти сделать
а еще: сделай такие же вещи, только со скоростью и высотой прыжка, где в скорости дефолтное значение 1.0, а в прыжке 2.0

добавление новых инструментов: WeaponService
Weapon.GetById(id) — возвращает название оружия по айди в виде строки
данная функция работает только с игроком! 

добавления в InventoryService
Inventory.Get(slot)
возвращает id оружия в определённом слоте
пример: player.Ui.Hint.Value = "Ваше основное оружие: " + Inventory.Get(player.Inventory.Main);

добавление в Area ну кароче чето там с тегами
вообще, хочу метод, чтобы получать все теги зон в виде массива
не помню, есть ли такое

изменение в таймерах: хочу таймеры, которые обрабатываются меньше чем за одну секунду
ну типо чтобы можно было запустить зацикленный таймер со временем 0.5

вроде все

**Comment by kkohno** [comment]
по порядку:
таймеры менее 1 сек могут много трафика начать есть... их специально так сделали
все тэги зон - если такого нет, то идея хорошая.
оружие мы специально по ID выдавать запретили - его нужно зарабатывать и покупать, по нашей концепции а не ставить в своих режимах.
С хп в безопасность упирается - получается можно сделать скрипт, который уж сильно будет контролировать других игроков и им может не понравиться это... тут нужно обдумывать ограничения.
А вот с картами - это годная идея. Вероятно прикрутим чтото подобное там.
