### ISSUE TITLE
Класс Blocks

### ISSUE THREAD

**Issue by Kukushechka7** [Sokol-Games-GmbH/PixelCombatsPublicApi#8]
Константин, предлагаю вам сделать класс Blocks, в котором будет метод, ну например
 `putBlock(blocksId, position);`
Также добавить кастомные Сеты блоков, чтобы можно было выбрать блоки для сета, и еще функцию `putAsset(assetName, position);` которая ставит кассеты.

**Comment by kkohno** [comment]
частично сделано
